### ISSUE TITLE
The use of @Inject annotation is incorrect ?

### ISSUE THREAD

**Issue by ckone35** [mulesoft/objectstore-connector#13]
This annotation is used 3 times in the class "org.mule.modules.ObjectStoreModule".

I may be mistaken, but for me.

none of the three cases can not work. Either the bean does not exist, or it is a method with too many parameters injection.

The code works for me in a sun jdk because the annotation does not exist and is therefore ignored.

By cons under ibm jdk, I have a ClassNotFoundException on javax.inject.Inject.

And when I add:

	<dependency>
	<groupId> javax.inject </ groupId>
	<artifactId> javax.inject </ artifactId>
	<version> 1 </ version>
	</ Dependency>

I have injection problems. 

I use the last version of this module (1.3) under Mule 3.4. 
To solve this problem i just unactivate the tag @Inject : replace the tag

	<context:annotation-config />

by

	<spring:bean class="org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor">
			<spring:property name="autowiredAnnotationTypes">
				<spring:list>
					<spring:value>org.springframework.beans.factory.annotation.Autowired</spring:value>
					<spring:value>org.springframework.beans.factory.annotation.Value</spring:value>
				</spring:list>
			</spring:property>
		</spring:bean>
		<spring:bean class="org.springframework.context.annotation.CommonAnnotationBeanPostProcessor" />
		<spring:bean class="org.springframework.beans.factory.annotation.RequiredAnnotationBeanPostProcessor" />

**Comment by sandipanbasu** [comment]
A new connector version is released recently, hence I would urge you to try this again and let us know about it if the issue persists !!
