### ISSUE TITLE
The documentation link is bad

### ISSUE THREAD

**Issue by granthbr** [mulesoft/objectstore-connector#28]
My app was working fine with the object store. now it is not. Resources online insist that I need to install the object store (i get the error below. I was not getting this error two weeks ago when I ran the application). Could someone fix the link for installation docs? 

org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'objectstore:config'. One of '{"http://www.springframework.org/schema/beans":beans, "http://www.springframework.org/schema/beans":bean, "http://www.springframework.org/schema/context":property-placeholder, "http://www.springframework.org/schema/beans":ref, "http://www.mulesoft.org/schema/mule/core":global-property, "http://www.mulesoft.org/schema/mule/core":configuration, "http://www.mulesoft.org/schema/mule/core":notifications, "http://www.mulesoft.org/schema/mule/core":abstract-extension, "http://www.mulesoft.org/schema/mule/core":abstract-shared-extension, "http://www.mulesoft.org/schema/mule/core":abstract-mixed-content-extension, "http://www.mulesoft.org/schema/mule/core":abstract-agent, "http://www.mulesoft.org/schema/mule/core":abstract-security-manager, "http://www.mulesoft.org/schema/mule/core":abstract-transaction-manager, "http://www.mulesoft.org/schema/mule/core":abstract-shared-transaction-manager, "http://www.mulesoft.org/schema/mule/core":abstract-connector, "http://www.mulesoft.org/schema/mule/core":abstract-shared-connector, "http://www.mulesoft.org/schema/mule/core":abstract-global-endpoint, "http://www.mulesoft.org/schema/mule/core":abstract-exception-strategy, "http://www.mulesoft.org/schema/mule/core":abstract-flow-construct, "http://www.mulesoft.org/schema/mule/core":flow, "http://www.mulesoft.org/schema/mule/core":sub-flow, "http://www.mulesoft.org/schema/mule/core":abstract-model, "http://www.mulesoft.org/schema/mule/core":abstract-interceptor-stack, "http://www.mulesoft.org/schema/mule/core":abstract-filter, "http://www.mulesoft.org/schema/mule/core":abstract-transformer, "http://www.mulesoft.org/schema/mule/core":processor-chain, "http://www.mulesoft.org/schema/mule/core":custom-processor, "http://www.mulesoft.org/schema/mule/core":invoke, "http://www.mulesoft.org/schema/mule/core":abstract-global-intercepting-message-processor, "http://www.mulesoft.org/schema/mule/core":custom-queue-store, "http://www.mulesoft.org/schema/mule/core":abstract-processing-strategy}' is expected.

**Comment by sandipanbasu** [comment]
Refer to the connector documentation (http://mulesoft.github.io/objectstore-connector/) for more information

**Comment by kro-agnitio** [comment]
I got the same error, i use objectstore in mule 3.5 and it wasn't problem previously. I can't switch from 3.5 into 3.6 which i the minimum version. How can I solve this?

**Comment by BeSolver** [comment]
Hey,
I am using object store in 3.5.1 version and i have switched my code from 3.5.1 to 3.6.2 ESB version and when try to run my program using object store  i am getting below exception( and i am not using  any java class for object store, just simple functionality i am using of object store like store,retrieve etc.)

Error creating bean with name 'ObjectStore': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.mule.api.registry.Registry org.mule.modules.objectstore.ObjectStoreConnector.registry; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.mule.api.registry.Registry] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}

Please advice
